"""Offline CLI tests for minimap calibration artifact generation."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import cv2
import numpy as np
from typer.testing import CliRunner

from valoscribe.__main__ import app
from valoscribe.maps.landmarks import decoded_image_sha256


def write_test_inputs(tmp_path: Path) -> tuple[Path, Path, Path]:
    frame = np.zeros((100, 120, 3), dtype=np.uint8)
    cv2.rectangle(frame, (24, 34), (67, 77), (210, 210, 210), 2)
    cv2.circle(frame, (48, 54), 9, (80, 80, 80), -1)
    cv2.line(frame, (25, 75), (65, 36), (255, 255, 255), 2)
    video = tmp_path / "synthetic.avi"
    writer = cv2.VideoWriter(str(video), cv2.VideoWriter_fourcc(*"MJPG"), 1.0, (120, 100))
    assert writer.isOpened()
    writer.write(frame)
    writer.release()

    hud = tmp_path / "hud.json"
    hud.write_text(
        json.dumps(
            {
                "name": "synthetic-profile",
                "calibration_status": "validated",
                "frame_width": 120,
                "frame_height": 100,
                "minimap": {"x": 20, "y": 30, "width": 48, "height": 48},
                "regions": {},
            }
        ),
        encoding="utf-8",
    )
    map_image = tmp_path / "canonical.png"
    assert cv2.imwrite(str(map_image), frame[30:78, 20:68])
    map_config = tmp_path / "map.json"
    map_config.write_text(
        json.dumps(
            {
                "map_id": "synthetic-map",
                "map_name": "Synthetic",
                "canonical_minimap": {
                    "image_url": "https://example.invalid/synthetic.png",
                    "local_asset_path": map_image.name,
                    "sha256": hashlib.sha256(map_image.read_bytes()).hexdigest(),
                    "asset_version": "synthetic-test",
                    "patch_version": "not-applicable",
                    "provenance": "Generated by this offline test.",
                },
                "geometry_status": "pending",
            }
        ),
        encoding="utf-8",
    )
    return video, hud, map_config


def decoded_label_hashes(video: Path, map_config: Path) -> tuple[str, str]:
    capture = cv2.VideoCapture(str(video))
    assert capture.isOpened()
    ok, frame = capture.read()
    capture.release()
    assert ok
    map_data = json.loads(map_config.read_text(encoding="utf-8"))
    canonical_path = map_config.parent / map_data["canonical_minimap"]["local_asset_path"]
    canonical = cv2.imread(str(canonical_path))
    assert canonical is not None
    return decoded_image_sha256(frame), decoded_image_sha256(canonical)


def test_calibrate_command_writes_five_artifacts_and_marks_pending_map(
    tmp_path: Path,
) -> None:
    video, hud, map_config = write_test_inputs(tmp_path)
    output = tmp_path / "calibration"

    result = CliRunner().invoke(
        app,
        [
            "minimap",
            "calibrate",
            "--video",
            str(video),
            "--timestamp",
            "00:00:00.000",
            "--hud-config",
            str(hud),
            "--map-config",
            str(map_config),
            "--output",
            str(output),
        ],
    )

    assert result.exit_code == 1, result.output
    expected = {
        "frame.png",
        "minimap_crop.png",
        "registered_minimap.png",
        "alignment_overlay.png",
        "diagnostics.json",
    }
    assert expected <= {path.name for path in output.iterdir()}
    diagnostics = json.loads((output / "diagnostics.json").read_text(encoding="utf-8"))
    assert diagnostics["profile_id"] == "synthetic-profile"
    assert diagnostics["map_asset_version"] == "synthetic-test"
    assert diagnostics["timestamp_seconds"] == 0.0
    assert diagnostics["passed"] is False
    assert diagnostics["failure_reason"] == "map_geometry_pending"
    assert diagnostics["transform_matrix"] is not None
    assert diagnostics["confidence"] is not None
    assert diagnostics["alignment_error"] is not None


def test_cli_calibration_passes_with_validated_registration_and_landmarks(
    tmp_path: Path,
) -> None:
    video, hud, map_config = write_test_inputs(tmp_path)
    map_data = json.loads(map_config.read_text(encoding="utf-8"))
    map_data.update(
        geometry_status="validated",
        walkable_areas=[
            {"polygon_id": "walkable", "vertices": [
                {"x": 0.0, "y": 0.0}, {"x": 1.0, "y": 0.0},
                {"x": 1.0, "y": 1.0}, {"x": 0.0, "y": 1.0},
            ]}
        ],
        site_polygons=[
            {"polygon_id": "site", "vertices": [
                {"x": 0.4, "y": 0.4}, {"x": 0.6, "y": 0.4},
                {"x": 0.6, "y": 0.6}, {"x": 0.4, "y": 0.6},
            ]}
        ],
        spawn_polygons=[
            {"polygon_id": "spawn", "vertices": [
                {"x": 0.0, "y": 0.0}, {"x": 0.2, "y": 0.0},
                {"x": 0.2, "y": 0.2}, {"x": 0.0, "y": 0.2},
            ]}
        ],
        named_zones=[{
            "zone_id": "zone",
            "polygon": {"polygon_id": "zone", "vertices": [
                {"x": 0.0, "y": 0.0}, {"x": 0.3, "y": 0.0},
                {"x": 0.3, "y": 0.3}, {"x": 0.0, "y": 0.3},
            ]},
        }],
        orientation_rules=["synthetic identity orientation"],
        registration_thresholds={
            "minimum_confidence": 0.0,
            "maximum_alignment_error": 1.0,
            "maximum_landmark_error_px": 2.0,
        },
    )
    map_config.write_text(json.dumps(map_data), encoding="utf-8")

    source_hash, canonical_hash = decoded_label_hashes(video, map_config)
    landmarks = tmp_path / "reviewed-landmarks.json"
    points = [(24, 24), (8, 8), (40, 40), (24, 8), (8, 24)]
    landmarks.write_text(
        json.dumps(
            {
                "provenance": "synthetic identity correspondences for CLI acceptance",
                "source_frame_sha256": source_hash,
                "canonical_asset_sha256": canonical_hash,
                "landmarks": [
                    {
                        "landmark_id": f"point-{index}",
                        "source_crop_point": {"x": x, "y": y},
                        "canonical_point": {"x": x, "y": y},
                    }
                    for index, (x, y) in enumerate(points)
                ],
            }
        ),
        encoding="utf-8",
    )
    output = tmp_path / "accepted-calibration"

    result = CliRunner().invoke(
        app,
        [
            "minimap",
            "calibrate",
            "--video",
            str(video),
            "--timestamp",
            "00:00:00.000",
            "--hud-config",
            str(hud),
            "--map-config",
            str(map_config),
            "--output",
            str(output),
            "--landmarks",
            str(landmarks),
        ],
    )

    assert result.exit_code == 0, result.output
    diagnostics = json.loads((output / "diagnostics.json").read_text(encoding="utf-8"))
    assert diagnostics["passed"] is True
    assert diagnostics["failure_reason"] is None
    evaluation = diagnostics["landmark_evaluation"]
    assert evaluation["acceptance_threshold_configured"] is True
    assert evaluation["maximum_error_threshold_px"] == 2.0
    assert evaluation["passed"] is True
    assert evaluation["point_count"] == len(points)
    assert evaluation["per_point_errors"] == [
        {"landmark_id": f"point-{index}", "error_px": 0.0}
        for index in range(len(points))
    ]
    assert evaluation["maximum_error_px"] == 0.0


def test_unlabeled_calibration_remains_provisional_with_validated_configs(
    tmp_path: Path,
) -> None:
    from valoscribe.commands.minimap import calibrate_video

    video, hud, map_config = write_test_inputs(tmp_path)
    map_data = json.loads(map_config.read_text(encoding="utf-8"))
    map_data.update(
        geometry_status="validated",
        walkable_areas=[
            {"polygon_id": "walkable", "vertices": [
                {"x": 0.0, "y": 0.0}, {"x": 1.0, "y": 0.0},
                {"x": 1.0, "y": 1.0}, {"x": 0.0, "y": 1.0},
            ]}
        ],
        site_polygons=[
            {"polygon_id": "site", "vertices": [
                {"x": 0.4, "y": 0.4}, {"x": 0.6, "y": 0.4},
                {"x": 0.6, "y": 0.6}, {"x": 0.4, "y": 0.6},
            ]}
        ],
        spawn_polygons=[
            {"polygon_id": "spawn", "vertices": [
                {"x": 0.0, "y": 0.0}, {"x": 0.2, "y": 0.0},
                {"x": 0.2, "y": 0.2}, {"x": 0.0, "y": 0.2},
            ]}
        ],
        named_zones=[{
            "zone_id": "zone",
            "polygon": {"polygon_id": "zone", "vertices": [
                {"x": 0.0, "y": 0.0}, {"x": 0.3, "y": 0.0},
                {"x": 0.3, "y": 0.3}, {"x": 0.0, "y": 0.3},
            ]},
        }],
        orientation_rules=["synthetic orientation"],
        registration_thresholds={
            "minimum_confidence": 0.0,
            "maximum_alignment_error": 1.0,
            "maximum_landmark_error_px": 2.0,
        },
    )
    map_config.write_text(json.dumps(map_data), encoding="utf-8")

    diagnostics = calibrate_video(video, "0", hud, map_config, tmp_path / "unlabeled")

    assert diagnostics["hud_calibration_status"] == "validated"
    assert diagnostics["map_geometry_status"] == "validated"
    assert diagnostics["passed"] is False
    assert diagnostics["failure_reason"] == "reviewed_landmarks_required"


def test_altered_canonical_asset_fails_file_hash_check_without_labels(
    tmp_path: Path,
) -> None:
    from valoscribe.commands.minimap import calibrate_video

    video, hud, map_config = write_test_inputs(tmp_path)
    map_data = json.loads(map_config.read_text(encoding="utf-8"))
    asset_path = map_config.parent / map_data["canonical_minimap"]["local_asset_path"]
    asset_path.write_bytes(asset_path.read_bytes() + b"altered")

    diagnostics = calibrate_video(video, "0", hud, map_config, tmp_path / "altered-asset")

    actual_hash = hashlib.sha256(asset_path.read_bytes()).hexdigest()
    assert diagnostics["passed"] is False
    assert diagnostics["failure_reason"] == (
        f"canonical_map_asset_sha256_mismatch:expected={map_data['canonical_minimap']['sha256']}"
        f":actual={actual_hash}"
    )
    assert diagnostics["canonical_asset_file_sha256"] == actual_hash


def test_optional_landmark_file_adds_errors_but_pending_map_stays_pending(
    tmp_path: Path,
) -> None:
    from valoscribe.commands.minimap import calibrate_video

    video, hud, map_config = write_test_inputs(tmp_path)
    labels = tmp_path / "landmarks.json"
    source_hash, canonical_hash = decoded_label_hashes(video, map_config)
    labels.write_text(
        json.dumps(
            {
                "provenance": "synthetic test points, not real map labels",
                "source_frame_sha256": source_hash,
                "canonical_asset_sha256": canonical_hash,
                "landmarks": [
                    {
                        "landmark_id": "center",
                        "source_crop_point": {"x": 24, "y": 24},
                        "canonical_point": {"x": 24, "y": 24},
                    }
                ],
            }
        ),
        encoding="utf-8",
    )

    diagnostics = calibrate_video(
        video, "0", hud, map_config, tmp_path / "labeled", landmarks_path=labels
    )

    assert diagnostics["landmark_evaluation"]["point_count"] == 1
    assert diagnostics["landmark_evaluation"]["maximum_error_px"] < 2.0
    assert diagnostics["landmark_evaluation"]["acceptance_threshold_configured"] is False
    assert diagnostics["landmark_evaluation"]["passed"] is False
    assert diagnostics["passed"] is False
    assert diagnostics["failure_reason"] == "landmark_acceptance_threshold_unconfigured"


def test_labels_bound_to_different_frame_fail_with_diagnostic(tmp_path: Path) -> None:
    from valoscribe.commands.minimap import calibrate_video

    video, hud, map_config = write_test_inputs(tmp_path)
    source_hash, canonical_hash = decoded_label_hashes(video, map_config)
    labels = tmp_path / "wrong-frame.json"
    labels.write_text(
        json.dumps(
            {
                "provenance": "synthetic labels",
                "source_frame_sha256": "0" * 64 if source_hash != "0" * 64 else "1" * 64,
                "canonical_asset_sha256": canonical_hash,
                "landmarks": [
                    {
                        "landmark_id": "center",
                        "source_crop_point": {"x": 24, "y": 24},
                        "canonical_point": {"x": 24, "y": 24},
                    }
                ],
            }
        ),
        encoding="utf-8",
    )

    diagnostics = calibrate_video(
        video, "0", hud, map_config, tmp_path / "wrong-frame", landmarks_path=labels
    )

    assert diagnostics["passed"] is False
    assert diagnostics["failure_reason"] == "landmark_source_frame_sha256_mismatch"


def test_labels_bound_to_different_canonical_asset_fail_with_diagnostic(tmp_path: Path) -> None:
    from valoscribe.commands.minimap import calibrate_video

    video, hud, map_config = write_test_inputs(tmp_path)
    source_hash, canonical_hash = decoded_label_hashes(video, map_config)
    labels = tmp_path / "wrong-map.json"
    labels.write_text(
        json.dumps(
            {
                "provenance": "synthetic labels",
                "source_frame_sha256": source_hash,
                "canonical_asset_sha256": "0" * 64
                if canonical_hash != "0" * 64
                else "1" * 64,
                "landmarks": [
                    {
                        "landmark_id": "center",
                        "source_crop_point": {"x": 24, "y": 24},
                        "canonical_point": {"x": 24, "y": 24},
                    }
                ],
            }
        ),
        encoding="utf-8",
    )

    diagnostics = calibrate_video(
        video, "0", hud, map_config, tmp_path / "wrong-map", landmarks_path=labels
    )

    assert diagnostics["passed"] is False
    assert diagnostics["failure_reason"] == "landmark_canonical_asset_sha256_mismatch"


def test_excessive_landmark_error_fails_configured_limit(tmp_path: Path) -> None:
    from valoscribe.commands.minimap import calibrate_video

    video, hud, map_config = write_test_inputs(tmp_path)
    map_data = json.loads(map_config.read_text(encoding="utf-8"))
    map_data["registration_thresholds"] = {
        "minimum_confidence": 0.0,
        "maximum_alignment_error": 1.0,
        "maximum_landmark_error_px": 1.0,
    }
    map_config.write_text(json.dumps(map_data), encoding="utf-8")
    source_hash, canonical_hash = decoded_label_hashes(video, map_config)
    labels = tmp_path / "bad-points.json"
    labels.write_text(
        json.dumps(
            {
                "provenance": "synthetic incorrect point",
                "source_frame_sha256": source_hash,
                "canonical_asset_sha256": canonical_hash,
                "landmarks": [
                    {
                        "landmark_id": "wrong",
                        "source_crop_point": {"x": 2, "y": 2},
                        "canonical_point": {"x": 40, "y": 40},
                    }
                ],
            }
        ),
        encoding="utf-8",
    )

    diagnostics = calibrate_video(
        video, "0", hud, map_config, tmp_path / "bad-points", landmarks_path=labels
    )

    assert diagnostics["landmark_evaluation"]["passed"] is False
    assert diagnostics["failure_reason"] == "landmark_error_above_configured_threshold"


def test_invalid_optional_landmark_file_fails_with_diagnostic(tmp_path: Path) -> None:
    from valoscribe.commands.minimap import calibrate_video

    video, hud, map_config = write_test_inputs(tmp_path)
    labels = tmp_path / "invalid-landmarks.json"
    labels.write_text('{"provenance":"","landmarks":[]}', encoding="utf-8")

    diagnostics = calibrate_video(
        video, "0", hud, map_config, tmp_path / "invalid-labels", landmarks_path=labels
    )

    assert diagnostics["passed"] is False
    assert diagnostics["failure_reason"].startswith("invalid_landmark_labels:")
    assert diagnostics["landmark_evaluation"] is None


def test_rotate_crop_transform_maps_original_coordinates_to_canonical() -> None:
    from valoscribe.commands.minimap import orient_minimap_crop

    crop = np.zeros((4, 6, 3), dtype=np.uint8)
    crop[1, 2] = (0, 0, 255)

    oriented, transform = orient_minimap_crop(crop, "rotate_90_ccw")

    assert oriented.shape == (6, 6, 3)
    destination = transform @ np.array([2.0, 1.0, 1.0])
    assert tuple(destination[:2]) == (2.0, 3.0)
    assert np.array_equal(oriented[3, 2], (0, 0, 255))


def test_pending_hud_calibration_cannot_pass_even_with_valid_map_geometry(
    tmp_path: Path,
) -> None:
    from valoscribe.commands.minimap import calibrate_video

    video, hud_path, map_path = write_test_inputs(tmp_path)
    hud = json.loads(hud_path.read_text(encoding="utf-8"))
    hud["calibration_status"] = "pending"
    hud_path.write_text(json.dumps(hud), encoding="utf-8")

    diagnostics = calibrate_video(video, "0", hud_path, map_path, tmp_path / "pending-hud")

    assert diagnostics["hud_calibration_status"] == "pending"
    assert diagnostics["failure_reason"] == "hud_minimap_profile_pending"
    assert diagnostics["passed"] is False


def test_calibrate_command_writes_diagnostics_for_missing_video(
    tmp_path: Path,
) -> None:
    _video, hud, map_config = write_test_inputs(tmp_path)
    output = tmp_path / "failed-calibration"

    result = CliRunner().invoke(
        app,
        [
            "minimap",
            "calibrate",
            "--video",
            str(tmp_path / "missing.avi"),
            "--timestamp",
            "5.5",
            "--hud-config",
            str(hud),
            "--map-config",
            str(map_config),
            "--output",
            str(output),
        ],
    )

    assert result.exit_code == 1
    diagnostics = json.loads((output / "diagnostics.json").read_text(encoding="utf-8"))
    assert diagnostics["passed"] is False
    assert diagnostics["failure_reason"] == "video_unavailable_or_unsupported"


def test_rotation_is_composed_into_source_to_canonical_transform() -> None:
    from valoscribe.commands.minimap import (
        _compose_source_transform,
        orient_minimap_crop,
    )
    from valoscribe.maps.registration import RegistrationResult

    crop = np.zeros((4, 6, 3), dtype=np.uint8)
    _, crop_to_oriented = orient_minimap_crop(crop, "rotate_90_ccw")
    registration = RegistrationResult(
        aligned_minimap=np.zeros((10, 10, 3), dtype=np.uint8),
        transform_matrix=((2.0, 0.0, 10.0), (0.0, 2.0, 20.0)),
        confidence=0.9,
        alignment_error=0.1,
        method="fixed",
        failure_reason=None,
    )

    composed = _compose_source_transform(registration, crop_to_oriented)

    assert composed.transform_matrix == ((0.0, 2.0, 12.0), (-2.0, 0.0, 30.0))


def test_vod_candidate_profile_and_reference_manifest_remain_pending() -> None:
    repository = Path(__file__).parents[2]
    profile = json.loads(
        (
            repository
            / "src/valoscribe/config/ascent_vct_americas_2026_stage2_final_1080p_candidate.json"
        ).read_text(encoding="utf-8")
    )
    manifest_path = (
        repository / "tests" / "fixtures" / "minimap_calibration_vod_manifest.json"
    )
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    assert profile["calibration_status"] == "pending"
    assert profile["minimap"] == {
        "x": 70,
        "y": 50,
        "width": 360,
        "height": 400,
        "orientation": "rotate_90_ccw",
    }
    assert manifest["acceptance"]["profile_status"] == "pending"
    assert manifest["acceptance"]["map_geometry_status"] == "pending"
    assert len(manifest["samples"]) >= 5
    assert {sample["half"] for sample in manifest["samples"]} == {1, 2}
    assert all("debug_artifacts" in sample for sample in manifest["samples"])


def test_timestamp_parser_accepts_clock_and_numeric_seconds() -> None:
    from valoscribe.commands.minimap import parse_timestamp

    assert parse_timestamp("00:01:02.500") == 62.5
    assert parse_timestamp("5.25") == 5.25
