"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, ChevronDown, Database, LoaderCircle, RefreshCw, Video } from "lucide-react";
import { Header } from "@/components/Header";
import { PreflightConfig, type StudioInput } from "@/components/PreflightConfig";
import { ExecutionTerminal, type TerminalLine } from "@/components/ExecutionTerminal";
import { TacticalRadar } from "@/components/TacticalRadar";
import { VideoDeck } from "@/components/VideoDeck";
import { RoundTimeline } from "@/components/RoundTimeline";
import { TacticalEventsFeed } from "@/components/TacticalEventsFeed";
import type { CorrectedObservation, ExcludedSpan, RoundManifestEntry, VODRoundManifest } from "@/lib/types";
import { summarizeCoverage } from "@/lib/coverage-summary";

type Example<T>={path:string;data:T}; type Vod={path:string;name:string;size:number}; type Run={runId:string;kind:"telemetry"|"plan-only"|"config-only";manifest:Record<string,unknown>;executionPlan?:import("@/lib/types").PlanOnlyRun|null;configSnapshot?:string|null;rounds:Array<{roundId:string;media:string[]}>;aggregate:Aggregate|null};
type SampleEvent={timestamp_seconds:number;sample_index:number;observed_marker_count:number;macro_counts:Record<string,number>;coverage_status:string;source_supported_observation_ids?:string[];tactical_eligible_observation_ids?:string[]}; type StoredEvent={timestamp_seconds?:number;direction?:string;source_supported_observation_ids?:string[];tactical_eligible_observation_ids?:string[];sample?:SampleEvent;persistence_window?:{start_timestamp_seconds?:number;end_timestamp_seconds?:number;coverage_numerator?:number;coverage_denominator?:number;confidence?:string};reversal_check_window?:{start_timestamp_seconds?:number;end_timestamp_seconds?:number;coverage_numerator?:number;coverage_denominator?:number;confidence?:string}}; type Aggregate={representative_rounds?:Array<{round_id:string;opening?:SampleEvent[];shift?:StoredEvent|null;regroup?:StoredEvent|null;commitment?:StoredEvent|null}>;recurring_patterns?:Array<{key:string;count:number;denominator:number}>;included_rounds?:string[]};
type Detail={kind?:"telemetry"|"plan-only"|"config-only";executionPlan?:import("@/lib/types").PlanOnlyRun;configSnapshot?:string|null;manifest:{rounds?:RoundManifestEntry[];teams?:Record<string,unknown>}|null;roundData:Array<{roundId:string;correctedObservations:CorrectedObservation[];rawObservationCount:number;summary?:{source_interval_seconds?:[number,number];observed_source_span_seconds?:[number,number];coverage_counts?:Record<string,number>;sample_count?:number;warnings?:string[]};sampleCoverage?:Array<{coverage_status:string}>;media:{canonicalPlayback:string;minimapPlayback:string}}>;aggregateSummary:Aggregate|null;availableRoundIds:string[]};
type ManifestData={presets:unknown[];manifests:Array<Example<VODRoundManifest>>;profiles:Array<Example<{profile_id:string;calibration_status:string}>>;vods:Vod[]};
const initialInput:StudioInput={vodPath:"",mapName:"ascent",matchId:"",mapId:"",fromRound:4,toRound:7,team:"100T",profilePath:"",manifestPath:"",outputDir:".local/runs/web-studio-analysis",verifySha:true};
const timeLabel=()=>new Date().toLocaleTimeString("en-GB",{hour12:false});
function mediaUrl(path:string){const relative=path.startsWith("../VOD/")?path.slice("../VOD/".length):path;return `/api/media/${relative.split("/").map(encodeURIComponent).join("/")}`;}

export default function Home(){
 const [data,setData]=useState<ManifestData|null>(null);const [runs,setRuns]=useState<Run[]>([]);const [runId,setRunId]=useState("");const [roundId,setRoundId]=useState("");const [detail,setDetail]=useState<Detail|null>(null);const [input,setInput]=useState(initialInput);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState("");const [preflightError,setPreflightError]=useState("");const [preflightBusy,setPreflightBusy]=useState(false);const [preflightStatus,setPreflightStatus]=useState("unconfigured");const [verifiedSha,setVerifiedSha]=useState("");const [planText,setPlanText]=useState("");const [lines,setLines]=useState<TerminalLine[]>([]);const [running,setRunning]=useState(false);const [notice,setNotice]=useState("");const [time,setTime]=useState(263);const [playing,setPlaying]=useState(false);const [rate,setRate]=useState(1);const [videoError,setVideoError]=useState(false);const [videoRequested,setVideoRequested]=useState(false);const [copied,setCopied]=useState(false);
 const selectedRun=runs.find((run)=>run.runId===runId)??null;
 const runRoundIds=Array.isArray(selectedRun?.manifest.round_ids)?selectedRun.manifest.round_ids.filter((value):value is string=>typeof value==="string"):[];
 const runSha=typeof selectedRun?.manifest.source_video_sha256==="string"?selectedRun.manifest.source_video_sha256:"";
 const runManifest=data?.manifests.map(item=>item.data).find(manifest=>manifest.source_video_sha256===runSha&&runRoundIds.every(id=>manifest.rounds.some(round=>round.round_id===id)))??null;
 const rounds=detail?.manifest?.rounds??runManifest?.rounds.filter(round=>runRoundIds.includes(round.round_id))??[];
 const activeRound=rounds.find((round)=>round.round_id===roundId)??rounds[0];
 const roundRecord=detail?.roundData.find((round)=>round.roundId===activeRound?.round_id);
 const markerData=roundRecord?.correctedObservations??[];
 const aggregate=detail?.aggregateSummary??selectedRun?.aggregate??null;
 const sourceVideo=useMemo(()=>{const identifier=selectedRun?.manifest.source_identifier;const vod=data?.vods.find(item=>item.name===identifier);return vod?mediaUrl(vod.path):""},[data,selectedRun]);
 const roundVideo=sourceVideo;
 const excluded=(activeRound?.excluded_spans??[]) as ExcludedSpan[];
 const begin=activeRound?.source_start_seconds??263;const finish=activeRound?.source_end_seconds??330;const live=activeRound?.live_start_seconds??begin;
 const addLine=useCallback((channel:string,text:string)=>setLines((current)=>[...current.slice(-100),{time:timeLabel(),channel,text}]),[]);
 const refreshRuns=useCallback(async()=>{const response=await fetch("/api/runs");if(!response.ok)throw new Error("Could not refresh stored runs.");const result=await response.json();const listed=(result.runs??[]) as Run[];setRuns(listed);return listed},[]);
 useEffect(()=>{let cancelled=false;void Promise.all([fetch("/api/manifests").then(async response=>{if(!response.ok)throw new Error((await response.json()).error??"Could not read local presets.");return response.json()}),fetch("/api/runs").then(async response=>{if(!response.ok)throw new Error((await response.json()).error??"Could not list existing runs.");return response.json()})]).then(([manifestData,runData])=>{if(cancelled)return;const manifests=(manifestData.manifests??[]) as Array<Example<VODRoundManifest>>;const profiles=(manifestData.profiles??[]) as Array<Example<{profile_id:string;calibration_status:string}>>;const vods=(manifestData.vods??[]) as Vod[];const listed=(runData.runs??[]) as Run[];setData({...manifestData,manifests,profiles,vods});setRuns(listed);const preset=manifests[0];const profile=profiles[0];const vod=vods[0];const preferred=listed.find((run)=>run.runId==="ascent-team-movement-mvp002-r3")??listed[0];if(preset)setInput({...initialInput,vodPath:vod?.path??"",mapName:preset.data.map_name,matchId:preset.data.match_id,mapId:preset.data.map_id,fromRound:4,toRound:7,team:Object.keys(preset.data.teams)[0]??"",manifestPath:preset.path,profilePath:profile?.path??"",outputDir:`.local/runs/web-studio-${Date.now()}`});if(preferred){setRunId(preferred.runId);const first=preferred.kind==="plan-only"?"":(preferred.manifest.round_ids as string[]|undefined)?.[0]??preferred.rounds[0]?.roundId??"";setRoundId(first);if(preferred.executionPlan)setPlanText(JSON.stringify(preferred.executionPlan,null,2));else if(preferred.configSnapshot)setPlanText(preferred.configSnapshot)}}).catch(error=>{if(!cancelled)setLoadError(error instanceof Error?error.message:"Local API unavailable. Start the loopback web server.")}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[]);
 useEffect(()=>{if(!runId||!roundId)return;let cancelled=false;setDetail(null);void fetch(`/api/runs/${encodeURIComponent(runId)}?round=${encodeURIComponent(roundId)}`).then(async response=>{if(!response.ok)throw new Error((await response.json()).error??"Run detail unavailable.");return response.json() as Promise<Detail>}).then(value=>{if(!cancelled){setDetail(value);const item=runManifest?.rounds.find(round=>round.round_id===roundId)??value.manifest?.rounds?.find(round=>round.round_id===roundId);if(item)setTime(item.source_start_seconds);else{const first=value.roundData[0]?.correctedObservations[0];if(first)setTime(first.source_timestamp_seconds)}}}).catch(error=>{if(!cancelled)setLoadError(error instanceof Error?error.message:"Unable to read selected run.")});return()=>{cancelled=true}},[runId,roundId,runManifest]);
 const updateInput=(next:StudioInput)=>{setInput(next);setPreflightStatus("unconfigured");setVerifiedSha("");setPlanText("");};
 async function preflight(){setPreflightBusy(true);setPreflightError("");setPreflightStatus("checking");setPlanText("");try{const response=await fetch("/api/preflight",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const result=await response.json();if(!response.ok)throw new Error(result.error??"Preflight failed closed.");setPreflightStatus("passed");setVerifiedSha(result.executionPlan.source_video_sha256);setPlanText(JSON.stringify(result.executionPlan,null,2));addLine("ok","Preflight passed · source SHA-256 and configured rounds verified.");addLine("plan",result.asciiSummary??"Execution plan ready.")}catch(error){setPreflightStatus("failed");setPreflightError(error instanceof Error?error.message:"Preflight failed. Check local source and manifest.");addLine("error",error instanceof Error?error.message:"Preflight failed.")}finally{setPreflightBusy(false)}}
 async function runJob(){const jobInput={...input,outputDir:`.local/runs/web-studio-${Date.now()}`};setInput(jobInput);setRunning(true);setNotice("");addLine("status","Starting local plan-only job; preflight will validate again.");try{const response=await fetch("/api/jobs/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(jobInput)});if(!response.ok){const result=await response.json();throw new Error(result.error??"Could not start job.")}if(!response.body)throw new Error("The local job stream returned no body.");const reader=response.body.getReader();const decoder=new TextDecoder();let buffer="";let event="message";while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split("\n\n");buffer=chunks.pop()??"";for(const chunk of chunks){for(const line of chunk.split("\n")){if(line.startsWith("event: "))event=line.slice(7);if(line.startsWith("data: ")){const payload=JSON.parse(line.slice(6));if(event==="log")addLine(payload.channel??"stdout",payload.text??"");else if(event==="status")addLine("status",payload.message??"Job running");else if(event==="complete"){addLine("complete",payload.message??"Plan job complete.");setNotice(payload.message??"Plan complete; no telemetry reconstruction was performed.");const updated=await refreshRuns();const completedId=jobInput.outputDir.split("/").at(-1)??"";const completed=updated.find((run)=>run.runId===completedId);if(completed){setRunId(completedId);setRoundId("");if(completed.executionPlan)setPlanText(JSON.stringify(completed.executionPlan,null,2));setDetail(null)}}else if(event==="error"){addLine("error",payload.message??"Job failed.");setNotice(payload.message??"Job failed.")}}}}}}catch(error){const message=error instanceof Error?error.message:"Job request failed.";addLine("error",message);setNotice(message)}finally{setRunning(false)}}
 const onSeek=(next:number)=>{setTime(Math.min(finish,Math.max(begin,next)));setVideoError(false);setVideoRequested(true)};
 const markerAt=markerData.length?markerData.reduce((nearest,marker)=>Math.abs(marker.source_timestamp_seconds-time)<Math.abs(nearest.source_timestamp_seconds-time)?marker:nearest,markerData[0]):null;
 function chooseRun(next:string){const item=runs.find((run)=>run.runId===next);setRunId(next);const first=item?.kind==="plan-only"||item?.kind==="config-only"?"":item?.rounds[0]?.roundId??(item?.manifest.round_ids as string[]|undefined)?.[0]??"";setRoundId(first);setPlanText(item?.executionPlan?JSON.stringify(item.executionPlan,null,2):item?.configSnapshot??"");setDetail(null);setVideoError(false);setVideoRequested(false)}
 async function copySha(){if(!verifiedSha)return;try{await navigator.clipboard.writeText(verifiedSha);setCopied(true);window.setTimeout(()=>setCopied(false),1200)}catch{addLine("error","Clipboard access denied; select the digest from the verified plan.")}}
 return <main id="workspace" className="studio-shell"><Header sha={verifiedSha} status={preflightStatus} onCopy={()=>void copySha()}/>{copied&&<span className="copy-feedback" role="status">SHA copied</span>}
 {loadError&&<div className="global-error" role="alert"><AlertTriangle size={16}/><span>{loadError}</span><button onClick={()=>window.location.reload()}><RefreshCw size={14}/> Retry</button></div>}
 <div className="workspace-heading"><div><h1>Round review</h1><p>Inspect the stored run, source positions and linked evidence. No player identities are inferred.</p></div><div className="run-controls"><label htmlFor="run-select">EXISTING RUN</label><div className="select-wrap"><Database size={14}/><select id="run-select" value={runId} onChange={(event)=>chooseRun(event.target.value)} disabled={!runs.length}><option value="">Choose a stored run</option>{runs.map((run)=><option key={run.runId} value={run.runId}>{run.runId}{run.kind==="plan-only"?" · PLAN ONLY":run.kind==="config-only"?" · CONFIG ONLY":""}</option>)}</select><ChevronDown size={13}/></div><label htmlFor="round-select">ROUND</label><select id="round-select" value={roundId} onChange={(event)=>{setRoundId(event.target.value);setVideoError(false);setVideoRequested(false)}} disabled={!rounds.length}>{rounds.map((round)=><option key={round.round_id} value={round.round_id}>R{round.map_round} · {round.status}</option>)}</select></div></div>{selectedRun?.kind==="plan-only"&&<section className="global-error" role="status"><Database size={16}/><span>Plan-only artifact · validated execution configuration; no telemetry, positions, playback, or tactical claims were generated.</span></section>}{selectedRun?.kind==="config-only"&&<section className="global-error" role="status"><Database size={16}/><span>Configuration snapshot found · no telemetry manifest or valid execution plan is available.</span></section>}
 {loading?<div className="loading-state"><LoaderCircle size={20}/>Loading local manifests and stored runs…</div>:<div className="studio-grid"><aside className="left-column"><PreflightConfig manifests={data?.manifests??[]} profiles={data?.profiles??[]} vods={data?.vods??[]} input={input} setInput={updateInput} onPreflight={()=>void preflight()} busy={preflightBusy} error={preflightError}/><ExecutionTerminal lines={lines} running={running} notice={notice} planText={planText} onRun={()=>void runJob()}/></aside>
 <section className="review-column">{selectedRun?.kind==="plan-only"&&<section className="events-panel"><div className="section-head"><div><span className="section-index">EXECUTION ARTIFACT</span><h2>Plan only · no telemetry</h2></div></div><p>This validated plan records source, selected rounds and configuration only. It contains no observations, reconstructed positions, playback or tactical evidence.</p><pre className="plan-json">{planText||JSON.stringify(selectedRun.executionPlan,null,2)}</pre></section>}{selectedRun?.kind==="config-only"&&<section className="events-panel"><h2>Config snapshot only</h2><p>No telemetry manifest or valid execution plan is present.</p><pre className="plan-json">{planText||selectedRun.configSnapshot||"No readable configuration snapshot."}</pre></section>}{selectedRun?.kind==="telemetry"&&<><div className="review-grid"><TacticalRadar observations={markerData} timestamp={time}/><section className="video-panel"><div className="section-head"><div><span className="section-index">{roundId||"NO ROUND SELECTED"} · SOURCE PLAYBACK</span><h2><Video size={17}/> Broadcast evidence</h2></div><span className="playback-tag">{playing?`${rate}× PLAYING`:"PAUSED"}</span></div>{roundId&&roundVideo&&videoRequested&&roundRecord?<VideoDeck key={`${roundId}-${roundVideo}`} src={roundVideo} time={time} start={begin} end={finish} playing={playing} rate={rate} onTime={onSeek} onPlaying={setPlaying} onError={()=>setVideoError(true)}/>:<div className="video-empty"><Video size={22}/><p>{roundId&&roundVideo?(roundRecord?"Source playback is paused until requested.":"Loading stored round evidence before playback."):"No playable video is attached to this round."}</p>{roundId&&roundVideo&&<button onClick={()=>setVideoRequested(true)} disabled={!roundRecord}>Load source VOD</button>}</div>}{videoError&&<div className="video-error" role="alert">This media file could not be played or reached. Try the source VOD or select another run.</div>}<div className="video-meta"><span>LOCAL SOURCE · SEEKABLE</span>{markerAt?<span>NEAREST SAMPLE {markerAt.source_timestamp_seconds.toFixed(2)}s · {markerAt.corrected?"SOURCE CORRECTED":"RAW CANDIDATE"}</span>:<span>NO OBSERVATION AT CURRENT TIME</span>}</div></section></div>
 {activeRound?<RoundTimeline roundNumber={activeRound.map_round} start={begin} end={finish} live={live} excluded={excluded} time={time} playing={playing} onSeek={onSeek} onPlay={()=>setPlaying(!playing)} onStep={(delta)=>onSeek(time+delta)} onRate={setRate} rate={rate} commitment={aggregate?.representative_rounds?.find((item)=>item.round_id===roundId)?.commitment}/>: <div className="timeline-unknown" role="status">No verified interval from a manifest matches this run. Round phase and timeline are withheld.</div>}
 <div className="lower-grid"><div className="coverage-strip"><span>ROUND COVERAGE</span><b>{summarizeCoverage(roundRecord?.sampleCoverage)}</b><small>Observation counts do not establish player or team completeness.</small></div><TacticalEventsFeed aggregate={aggregate} roundId={roundId} manifest={runManifest} onSeek={onSeek}/></div>
 </>}</section></div>}
 <footer className="footer-bar"><span>VALOSCRIBE / LOCAL INSPECTION WORKSPACE</span><span>{selectedRun?.kind==="plan-only"?`${selectedRun.runId} · PLAN ONLY · ${selectedRun.executionPlan?.selected_rounds.length??0} PLANNED ROUNDS`:selectedRun?.kind==="config-only"?`${selectedRun.runId} · CONFIG ONLY`:selectedRun?`${selectedRun.runId} · ${selectedRun.rounds.length} ROUNDS`:"NO STORED RUN SELECTED"}</span><span>UNKNOWN STAYS UNKNOWN</span></footer></main>;
}
