import { ArrowUpRight, CircleDot, Quote } from "lucide-react";
type CitedSample = { timestamp_seconds: number; sample_index: number; observed_marker_count: number; macro_counts: Record<string,number>; coverage_status: string; source_supported_observation_ids?: string[]; tactical_eligible_observation_ids?: string[] };
type EventRecord = { timestamp_seconds?: number; direction?: string; source_supported_observation_ids?: string[]; tactical_eligible_observation_ids?: string[]; sample?: CitedSample; persistence_window?: WindowRecord; reversal_check_window?: WindowRecord };
type WindowRecord = { start_timestamp_seconds?: number; end_timestamp_seconds?: number; coverage_numerator?: number; coverage_denominator?: number; confidence?: string };
type RepresentativeRound = { round_id: string; opening?: CitedSample[]; shift?: EventRecord|null; regroup?: EventRecord|null; commitment?: EventRecord|null };
type Aggregate = { representative_rounds?: RepresentativeRound[]; recurring_patterns?: Array<{key:string;count:number;denominator:number}>; included_rounds?:string[] };

export function TacticalEventsFeed({aggregate,roundId,manifest,onSeek}:{aggregate:Aggregate|null;roundId:string;manifest:{rounds?:Array<{round_id:string;map_round:number}>}|null;onSeek:(time:number)=>void}) {
 const round=aggregate?.representative_rounds?.find((item)=>item.round_id===roundId);const entries=round?.opening??[];const roundNumber=manifest?.rounds?.find((item)=>item.round_id===roundId)?.map_round;
 const sourceEvents=[...(round?.shift?[{label:"Observed shift",event:round.shift}]:[]),...(round?.regroup?[{label:"Observed regroup direction",event:round.regroup}]:[]),...(round?.commitment?[{label:"Stored commitment candidate",event:round.commitment}]:[])];
 const evidenceIds=(sample:CitedSample|undefined)=>sample?.source_supported_observation_ids?.length?sample.source_supported_observation_ids:sample?.tactical_eligible_observation_ids??[];
 return <section className="events-panel" aria-labelledby="events-title"><div className="section-head"><div><span className="section-index">SOURCE-BOUND RECORDS</span><h2 id="events-title">Evidence &amp; patterns</h2></div><span className="evidence-count">{entries.length||sourceEvents.length?`${entries.length+sourceEvents.length} CITED RECORD${entries.length+sourceEvents.length===1?"":"S"}`:"NO CITED EVENTS"}</span></div>
 {entries.length||sourceEvents.length?<div className="evidence-list">
 {entries.map((entry,index)=>{const id=evidenceIds(entry)[0];return <article className="evidence-item" key={`opening-${entry.sample_index}-${index}`}><div className="event-mark"><CircleDot size={15}/></div><div className="evidence-body"><div className="evidence-row"><b>Observed opening occupancy</b><time>{entry.timestamp_seconds.toFixed(2)}s</time></div><p>{Object.entries(entry.macro_counts).filter(([key])=>key!=="OTHER"&&key!=="SPAWN").map(([key,value])=>`${key} ${value}`).join(" · ")} <span>· {entry.coverage_status} coverage · {entry.observed_marker_count} candidate markers</span></p><button className="citation" disabled={!id} onClick={()=>onSeek(entry.timestamp_seconds)}><Quote size={11}/>{id?`${id} · R${roundNumber??"?"} · ${entry.timestamp_seconds.toFixed(2)}s`:`R${roundNumber??"?"} · ${entry.timestamp_seconds.toFixed(2)}s`}<ArrowUpRight size={11}/></button></div></article>})}
 {sourceEvents.map(({label,event})=>{const sample=event.sample;const timestamp=sample?.timestamp_seconds??event.timestamp_seconds;const ids=evidenceIds(sample).length?evidenceIds(sample):event.source_supported_observation_ids?.length?event.source_supported_observation_ids:event.tactical_eligible_observation_ids??[];const window=event.persistence_window;const reversal=event.reversal_check_window;const count=sample?.observed_marker_count;const zones=sample?.macro_counts?Object.entries(sample.macro_counts).filter(([key,value])=>key!=="OTHER"&&key!=="SPAWN"&&value>0).map(([key,value])=>`${key} ${value}`).join(" · "):"";return <article className="evidence-item" key={label}><div className="event-mark"><CircleDot size={15}/></div><div className="evidence-body"><div className="evidence-row"><b>{label}</b>{timestamp!==undefined&&<time>{timestamp.toFixed(2)}s</time>}</div><p>{event.direction?`Direction ${event.direction} · `:""}{zones?`${zones} · `:""}{count!==undefined?`${count} observed markers · `:""}{sample?.coverage_status?`${sample.coverage_status} coverage · `:""}{window&&`persistence-window coverage ${window.coverage_numerator??"?"}/${window.coverage_denominator??"?"} · `}{reversal&&`reversal-check coverage ${reversal.coverage_numerator??"?"}/${reversal.coverage_denominator??"?"} · `}{window?.confidence??"stored source-backed event; interpretation remains partial"}</p>{timestamp!==undefined&&<button className="citation" onClick={()=>onSeek(timestamp)}><Quote size={11}/>R{roundNumber??"?"} · {timestamp.toFixed(2)}s<ArrowUpRight size={11}/></button>}{ids.map((id)=><button className="citation" key={id} onClick={()=>timestamp!==undefined&&onSeek(timestamp)} disabled={timestamp===undefined}><Quote size={11}/>{id} · R{roundNumber??"?"} · {timestamp?.toFixed(2)??"?"}s<ArrowUpRight size={11}/></button>)}</div></article>})}
 </div>:<div className="empty-evidence"><CircleDot size={18}/><p>No source-cited events are stored for this round.</p><span>Choose an available run and round; patterns are never synthesized.</span></div>}
 {aggregate?.recurring_patterns?.length?<div className="patterns"><div className="matrix-title"><span>STORED AGGREGATE PATTERNS</span><span>n / {aggregate.included_rounds?.length??"?"} rounds</span></div>{aggregate.recurring_patterns.map((pattern)=><div key={pattern.key} className="pattern-row"><span>{pattern.key}</span><b>{pattern.count}<small> / {pattern.denominator}</small></b></div>)}<p>Partial observations only; not a full-team distribution or identity claim.</p></div>:null}
 </section>;
}
